social_media_planner/urls.py
from django.conf.urls import url


from . import views

urlpatterns = [
    url(r'^$', views.SocialMediaPlannerView.as_view(), name='social_media_planner'),
    
    url(r'^notifications/send-test/$',
        views.SendTestNotificationView.as_view(), name='send_test_notification'),

    url(r'^user-profile/notifications/edit/$',
        views.UserProfileNotificationsEditView.as_view(), name='user_profile_notifications_edit'),

    url(r'^meeting/$', views.MeetingListView.as_view(), name='meeting_list'),
    url(r'^meeting/add/$', views.MeetingCreateView.as_view(), name='meeting_add',),
    url(r'^meeting/(?P<pk>\d+)/$', views.MeetingDetailView.as_view(), name='meeting_detail',),
    url(r'^meeting/(?P<pk>\d+)/edit/$', views.MeetingEditView.as_view(), name='meeting_edit',),
    url(r'^meeting/(?P<pk>\d+)/delete/$', views.MeetingDeleteView.as_view(), name='meeting_delete',),

    url(r'^category/$', views.CategoryListView.as_view(), name='category_list'),
    url(r'^category/add/$', views.CategoryCreateView.as_view(), name='category_add',),
    url(r'^category/(?P<pk>\d+)/$', views.CategoryDetailView.as_view(), name='category_detail',),
    url(r'^category/(?P<pk>\d+)/edit/$', views.CategoryEditView.as_view(), name='category_edit',),
    url(r'^category/(?P<pk>\d+)/delete/$', views.CategoryDeleteView.as_view(), name='category_delete',),

    url(r'^key-content/$', views.KeyContentListView.as_view(), name='key_content_list'),
    url(r'^key-content/add/$', views.KeyContentCreateView.as_view(), name='key_content_add',),
    url(r'^key-content/(?P<pk>\d+)/$', views.KeyContentDetailView.as_view(), name='key_content_detail',),
    url(r'^key-content/(?P<pk>\d+)/edit/$', views.KeyContentEditView.as_view(), name='key_content_edit',),
    url(r'^key-content/(?P<pk>\d+)/delete/$', views.KeyContentDeleteView.as_view(), name='key_content_delete',),

    url(r'^post-content-type/$', views.PostContentTypeListView.as_view(), name='post_content_type_list'),
    url(r'^post-content-type/add/$', views.PostContentTypeCreateView.as_view(), name='post_content_type_add',),
    url(r'^post-content-type/(?P<pk>\d+)/$', views.PostContentTypeDetailView.as_view(), name='post_content_type_detail',),
    url(r'^post-content-type/(?P<pk>\d+)/edit/$', views.PostContentTypeEditView.as_view(), name='post_content_type_edit',),
    url(r'^post-content-type/(?P<pk>\d+)/delete/$', views.PostContentTypeDeleteView.as_view(), name='post_content_type_delete',),

    url(r'^post/$', views.PostListView.as_view(), name='post_list'),
    url(r'^post/add/$', views.PostCreateView.as_view(), name='post_add',),
    url(r'^post/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='post_detail',),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostEditView.as_view(), name='post_edit',),
    url(r'^post/(?P<pk>\d+)/delete/$', views.PostDeleteView.as_view(), name='post_delete',),
    url(r'^post/(?P<pk>\d+)/attach-files/$', views.PostAttachFilesView.as_view(), name='post_attach_files',),
    url(r'^post/(?P<pk>\d+)/edit-attachments/$', views.PostEditAttachmentsView.as_view(), name='post_edit_attachments',),

    url(r'^post/(?P<post_id>\d+)/content/add/$', views.PostContentCreateView.as_view(), name='post_content_add',),
    url(r'^post/(?P<post_id>\d+)/content/(?P<pk>\d+)/edit/$', views.PostContentEditView.as_view(), name='post_content_edit',),
    url(r'^post/(?P<post_id>\d+)/content/(?P<pk>\d+)/delete/$', views.PostContentDeleteView.as_view(), name='post_content_delete',),
    url(r'^post/(?P<post_id>\d+)/content/(?P<pk>\d+)/validate/(?P<type_name>grammar|content|post_content_type)/$',
        views.PostContentValidateView.as_view(), name='post_content_validate',),
    url(r'^post/(?P<post_id>\d+)/content/(?P<pk>\d+)/invalidate/(?P<type_name>grammar|content|post_content_type)/$',
        views.PostContentInvalidateView.as_view(), name='post_content_invalidate',),
    url(r'^post/(?P<post_id>\d+)/content/(?P<pk>\d+)/publish/$',
        views.PostContentPublishView.as_view(), name='post_content_publish',),

    url(r'^post/(?P<post_id>\d+)/content/(?P<post_content_id>\d+)/review/add/$',
        views.PostContentReviewCreateView.as_view(), name='post_content_review_add',),
    url(r'^post/(?P<post_id>\d+)/content/(?P<post_content_id>\d+)/review/(?P<pk>\d+)/edit/$',
        views.PostContentReviewEditView.as_view(), name='post_content_review_edit',),
    url(r'^post/(?P<post_id>\d+)/content/(?P<post_content_id>\d+)/review/(?P<pk>\d+)/delete/$',
        views.PostContentReviewDeleteView.as_view(), name='post_content_review_delete',),
    url(r'^post/(?P<post_id>\d+)/content/(?P<post_content_id>\d+)/review/(?P<pk>\d+)/validate/(?P<type_name>review)/$',
        views.PostContentReviewValidateView.as_view(), name='post_content_review_validate',),
    url(r'^post/(?P<post_id>\d+)/content/(?P<post_content_id>\d+)/review/(?P<pk>\d+)/invalidate/(?P<type_name>review)/$',
        views.PostContentReviewInvalidateView.as_view(), name='post_content_review_invalidate',),
    url(r'^post/(?P<post_id>\d+)/content/(?P<post_content_id>\d+)/review/(?P<pk>\d+)/set-as-content/$',
        views.PostContentReviewSetAsContentView.as_view(), name='post_content_review_set_as_content',),
]

social_media_planner/models.py
from __future__ import unicode_literals

import datetime

from django.conf import settings as dj_settings
from django.contrib.auth.signals import user_logged_in
from django.core.urlresolvers import reverse
from django.db import models

from mptt.models import MPTTModel, TreeForeignKey
from slugify import slugify
from taggit.managers import TaggableManager

from django_utils.models import AuditLogMixin, ObjectStatus
from model_attachments.models import AttachmentMixin

import settings


POST_CONTENT_REVIEW_TYPES = (
    ('note', 'Note'),
    ('important', 'Important'),
    ('warning', 'Warning'),
    ('rewrite', 'Rewrite'),
)


class Attachment(AttachmentMixin):
    category = models.ForeignKey(ObjectStatus, null=True, blank=True,
        limit_choices_to={'model_class_name_tag': 'social_media_planner.Attachment.category'},
        related_name='social_media_planner_attachments')

    class Meta:
        ordering = ('file_type', 'name')

    def get_absolute_url(self):
        return reverse('social_media_planner:meeting_detail', kwargs={'pk': self.pk})


class MeetingManager(models.Manager):

    def get_next_meeting(self):
        try:
            return super(MeetingManager, self).filter(meeting_date__gte=datetime.datetime.now())[0]
        except IndexError:
            return None


class Meeting(AuditLogMixin):
    title = models.CharField(max_length=200)
    meeting_date = models.DateTimeField()
    participants = models.ManyToManyField(getattr(dj_settings, 'AUTH_USER_MODEL', 'auth.User'),
                                          related_name='social_media_planner_meetings', blank=True)
    topics = models.TextField(default='', blank=True)
    short_report = models.TextField(default='', blank=True)

    objects = MeetingManager()

    def __str__(self):
        return '{title} ({meeting_date})'.\
            format(title=self.title, meeting_date=str(self.meeting_date))

    def __unicode__(self):
        return u'{title} ({meeting_date})'.\
            format(title=self.title, meeting_date=str(self.meeting_date))

    def get_absolute_url(self):
        return reverse('social_media_planner:meeting_detail', kwargs={'pk': self.pk})


class KeyContent(MPTTModel):
    label = models.CharField(max_length=100)
    codename = models.CharField(max_length=50, default='', blank=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='subkeys', db_index=True)
    key_content_color = models.CharField(max_length=7, default='', blank=True)
    key_content_text_color = models.CharField(max_length=7, default='#FFFFFF', blank=True,
        help_text='Reverse color (if color is used as background), default is white')

    def __str__(self):
        label = '{label}'.format(label=self.label)
        if self.parent:
            label += ' ({label_path})'.format(label_path=self.parents_label_path)
        return label

    def __unicode__(self):
        label = '{label}'.format(label=self.label)
        if self.parent:
            label += ' ({label_path})'.format(label_path=self.parents_label_path)
        return unicode(label)

    def save(self, *args, **kwargs):
        if not self.codename:
            self.codename = slugify(self.label, to_lower=True)
        super(KeyContent, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('social_media_planner:key_content_detail', kwargs={'pk': self.pk})

    @property
    def parents_label_path(self):
        if not self.parent:
            return ''
        labels = []
        parent = self.parent
        while parent:
            labels.append(parent.label)
            parent = parent.parent
        return ' > '.join(sorted(labels, reverse=True))

    @property
    def color(self):
        if self.key_content_color:
            return self.key_content_color
        key_content_color = ''
        parent = self.parent
        while key_content_color == '' and parent:
            key_content_color = parent.key_content_color
            parent = parent.parent
        return key_content_color


class Category(models.Model):
    """ i.e. Events, Product launches, Promotions, Monthly marketing headlines
    """
    label = models.CharField(max_length=100)
    codename = models.CharField(max_length=50, default='', blank=True)
    icon = models.CharField(max_length=50, default='', blank=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return '{label}'.format(label=self.label)

    def __unicode__(self):
        return u'{label}'.format(label=self.label)

    def save(self, *args, **kwargs):
        if not self.codename:
            self.codename = slugify(self.label, to_lower=True)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('social_media_planner:category_detail', kwargs={'pk': self.pk})


class PostContentType(models.Model):
    """ i.e. Twitter, Facebook, Linkedin
    - `icon`: icon name (i.e. 'fa-twitter')
    """
    label = models.CharField(max_length=100)
    codename = models.CharField(max_length=50, default='', blank=True)
    icon = models.CharField(max_length=50, default='', blank=True)

    def __str__(self):
        return '{label}'.format(label=self.label)

    def __unicode__(self):
        return u'{label}'.format(label=self.label)

    def save(self, *args, **kwargs):
        if not self.codename:
            self.codename = slugify(self.label, to_lower=True)
        super(PostContentType, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('social_media_planner:post_content_type_detail', kwargs={'pk': self.pk})


class Post(AuditLogMixin):
    label = models.CharField(max_length=200)
    post_reason = models.TextField(default='', blank=True,
        help_text='What\'s going on / content themes')
    publish_date = models.DateField(null=True, blank=True)
    publish_date_from = models.DateField(null=True, blank=True)
    publish_date_to = models.DateField(null=True, blank=True)
    status = models.ForeignKey(ObjectStatus, null=True, blank=True,
        limit_choices_to={'model_class_name_tag': 'social_media_planner.Post.status'},
        related_name='post_statuses')
    expected_impact = models.PositiveSmallIntegerField(
        default=1, help_text='1 (low impact) to 10 (high impact)')
    feedback = models.TextField(default='', blank=True, help_text='Insights, results')
    help_needed = models.BooleanField(default=False)
    help_needed_from = models.ManyToManyField(
        getattr(dj_settings, 'AUTH_USER_MODEL', 'auth.User'),
        related_name='social_media_planner_help_with_posts', blank=True)
    publishers = models.ManyToManyField(
        getattr(dj_settings, 'AUTH_USER_MODEL', 'auth.User'),
        related_name='social_media_planner_publisher_posts', blank=True)

    tags = TaggableManager(blank=True)
    key_content = models.ForeignKey(KeyContent)
    category = models.ForeignKey(Category)
    attachments = models.ManyToManyField(Attachment, blank=True)

    class Meta:
        permissions = (
            ("can_validate_post_grammar", "Can validate post grammar"),
            ("can_validate_post_content", "Can validate post content"),
            ("can_validate_post_post_content_type", "Can validate post content type"),
            ("can_manage_post_content_reviews", "Can manage post content reviews"),
            ("can_publish_post", "Can publish post"),
            ("can_manage_post_attachments", "Can manage attachments to post"),
        )

    def __str__(self):
        return '{label}'.format(label=self.label)

    def __unicode__(self):
        return u'{label}'.format(label=self.label)

    def save(self, *args, **kwargs):
        self.expected_impact = min(10, max(0, self.expected_impact))
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('social_media_planner:post_detail', kwargs={'pk': self.pk})

    @property
    def attached_files_path(self):
        return settings.SOCIAL_MEDIA_PLANNER['PATHS']['post'].\
            format(id=self.id, media=dj_settings.MEDIA_ROOT)

    def get_attachment_delete_url(self, attached_file_pk):
        return reverse('social_media_planner:post_attached_file_delete',
                       kwargs={'pk': self.pk, 'attached_file_pk': attached_file_pk})


class PostContent(AuditLogMixin):
    """
    - `content_checked`: the post content has been approved
    - `grammar_checked`: the grammar is ok
    - `shares`: approx. number of shares on social
    - `favourites`: approx. number of favourites or likes on social
    """
    post = models.ForeignKey(Post, related_name='post_contents')
    title = models.CharField(
        max_length=200, default='', blank=True, help_text='Title to be used in final post')
    content = models.TextField(default='', blank=True)
    content_notes = models.TextField(default='', blank=True, help_text="Revision notes on content")
    post_content_type = models.ForeignKey(PostContentType)
    language = models.CharField(max_length=7, choices=dj_settings.LANGUAGES, default='en')
    final_link = models.TextField(default='', blank=True)
    content_checked = models.BooleanField(default=False)
    content_checked_by = models.ForeignKey(
        getattr(dj_settings, 'AUTH_USER_MODEL', 'auth.User'), null=True, blank=True,
        related_name='posts_content_checked')
    content_checked_date = models.DateField(null=True, blank=True)
    grammar_checked = models.BooleanField(default=False)
    grammar_checked_by = models.ForeignKey(
        getattr(dj_settings, 'AUTH_USER_MODEL', 'auth.User'), null=True, blank=True,
        related_name='posts_grammar_checked')
    grammar_checked_date = models.DateField(null=True, blank=True)
    post_content_type_checked = models.BooleanField(default=False)
    post_content_type_checked_by = models.ForeignKey(
        getattr(dj_settings, 'AUTH_USER_MODEL', 'auth.User'), null=True, blank=True,

social_media_planner/templates/social_media_planner/materialize/category/category.html
{% extends "social_media_planner/materialize/social_media_planner.html" %}


{% block breadcrumbs %}
  {{ block.super }}
  <i class="fa fa-angle-right"></i>
  <a href="{% url 'social_media_planner:category_list' %}">Categories</a>
{% endblock breadcrumbs %}


{% block sidebar_title %}
  Categories
{% endblock sidebar_title %}


{% block sidebar %}
  {{ block.super }}
  <a href="{% url 'social_media_planner:category_list' %}" class="collection-item"><i class="fa fa-list"></i> List categories</a>
  {% if perms.social_media_planner.change_category %}
    <a href="{% url 'social_media_planner:category_add' %}" class="collection-item"><i class="fa fa-plus"></i> Add category</a>
  {% endif %}
{% endblock sidebar %}

social_media_planner/templates/social_media_planner/materialize/category/category_confirm_delete.html
{% extends "social_media_planner/materialize/category/category_detail.html" %}


{% block page_title %}
  <i class="fa fa-comments"></i> Delete "{{ category }}"
{% endblock page_title %}


{% block breadcrumbs %}
  {{ block.super }}
  <i class="fa fa-angle-right"></i>
  <a href="{% url 'social_media_planner:category_delete' category.id %}">Delete</a>
{% endblock breadcrumbs %}


{% block content %}

  <div class="bs-callout bs-callout-danger">
    <p>Are you sure you want to delete this category?</p>
    <div class="align-center">
      <form action="{% url 'social_media_planner:category_delete' category.id %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn red" value="Delete" />
        <a href="{{ category.get_absolute_url }}" class="btn">Back to category</a>
      </form>

    </div>
  </div>

{% endblock content %}

social_media_planner/templates/social_media_planner/materialize/category/category_detail.html
{% extends "social_media_planner/materialize/category/category.html" %}


{% block sidebar %}
  {{ block.super }}
  <!--PERMESSIHERE-->
  {% if perms.social_media_planner.change_category %}
    <a href="{% url 'social_media_planner:category_edit' category.id %}" class="collection-item"><i class="fa fa-edit"></i> Edit category</a>
  {% endif %}
  {% if perms.social_media_planner.delete_category %}
    <a href="{% url 'social_media_planner:category_delete' category.id %}" class="collection-item"><i class="fa fa-times"></i> Delete category</a>
  {% endif %}
{% endblock sidebar %}


{% block breadcrumbs %}
  {{ block.super }}
  <i class="fa fa-angle-right"></i>
  <a href="{{ category.get_absolute_url }}">{{ category.label }}</a>
{% endblock breadcrumbs %}


{% block page_title %}
  {{ category.label }}
{% endblock page_title %}

{% block content %}

  <div class="row">
    <div class="col s12 m6">
      <table class="table">
        <tr>
          <th>Label</th>
          <td>{{ category.label }}</td>
        </tr>
        <tr>
          <th>Codename</th>
          <td>{{ category.codename }}</td>
        </tr>
        <tr>
          <th>Icon</th>
          <td>
            {{ category.icon }}
            {% if category.icon %}
              <i class="fa {{ category.icon }}"></i>
            {% endif %}
          </td>
        </tr>
      </table>
    </div>
    <div class="col s12 m6">
    </div>
  </div>


{% endblock content %}

social_media_planner/templates/social_media_planner/materialize/category/category_form.html
{% extends category|yesno:"social_media_planner/materialize/category/category_detail.html,social_media_planner/materialize/category/category.html" %}


{% block extra_css_plugins %}
  {{ block.super }}
  {% include "social_media_dashboard/shortcuts/forms_css.html" %}
{% endblock extra_css_plugins %}


{% block extra_scripts %}
  {{ block.super }}
  {% include "social_media_dashboard/shortcuts/forms_js.html" %}
  {% include "django_helper_forms/forms/materialize/scripts.html" %}
{% endblock extra_scripts %}


{% block page_title %}
  <i class="fa fa-sitemap"></i>
  {% if category %}
    Edit "{{ category }}"
  {% else %}
    Create category
  {% endif %}
{% endblock page_title %}


{% block breadcrumbs %}
  {{ block.super }}
  <i class="fa fa-angle-right"></i>
  {% if category %}
    <a href="{% url 'social_media_planner:category_edit' category.id %}">Edit</a>
  {% else %}
    <a href="{% url 'social_media_planner:category_add' %}">Add</a>
  {% endif %}
{% endblock breadcrumbs %}


{% block content %}

  <form action="{{ request.get_full_path }}" method="post" id="category_form" class="django form-horizontal">
    {% csrf_token %}

    {% include "django_helper_forms/forms/materialize/form_template.html" %}

    {% include "django_helper_forms/forms/materialize/form_template_bottom.html" %}

  </form>

{% endblock content %}

social_media_planner/templates/social_media_planner/materialize/category/category_list.html
{% extends "social_media_planner/materialize/category/category.html" %}


{% block content %}

  <table class="table table-striped table-objects-list table-hover" id="categorys_list">
    <thead>
    <tr>
      <th>Label</th>
      {% if request.user.is_superuser %}
        <th>Codename</th>
      {% endif %}
      <th>Icon</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    {% for category in object_list %}
      <tr>
        <td>
          <a href="{% url 'social_media_planner:category_detail' category.id %}">
            {{ category.label }}
          </a>
        </td>
        {% if request.user.is_superuser %}
          <td>
            {{ category.codename }}
          </td>
        {% endif %}
        <td>
          <i class="fa {{ category.icon }}"></i>
        </td>
        <td>
          <!--PERMESSIHERE-->
          {% if perms.social_media_planner.change_category %}
            <a href="{% url 'social_media_planner:category_edit' category.id %}"><i class="fa fa-edit"></i></a>
          {% endif %}
          {% if perms.social_media_planner.delete_category %}
            <a href="{% url 'social_media_planner:category_delete' category.id %}"><i class="fa fa-times"></i></a>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock content %}